"""Regression tests for the transcript miners. Stdlib only.

Run from the repo root:  python -m unittest

Fixtures are synthetic JSONL transcripts written to a temp dir — no real user
data. Each case is pinned to a bug found on v0.3.0 real-world output.
"""
import datetime
import json
import os
import shutil
import sys
import tempfile
import unittest

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPTS = os.path.join(HERE, "..", "plugins", "gripe-miner", "scripts")
sys.path.insert(0, os.path.abspath(SCRIPTS))

from lib import transcripts  # noqa: E402
from lib.transcripts import strip_injections, iter_prompts, mine, command_invocation, timestamp_epoch  # noqa: E402
from lib.classify_asks import INJECTED_RE, ACK_RE, ineligible_reason, cluster, usage_totals  # noqa: E402
from lib.classify_gripes import classify as classify_gripe  # noqa: E402

CAVEAT = ("<local-command-caveat>Caveat: The messages below were generated by the user "
          "while running local commands. DO NOT respond to these messages or otherwise "
          "consider them in your response unless the user explicitly asks you to."
          "</local-command-caveat>")
NUDGE_NEW = ("Your response above was cut off mid-stream. Resume directly from where it "
             "stops — no apology, no recap. If none of it survived, answer the request from the start.")
NUDGE_OLD = "Your response above was stopped by the token limit. Please continue."
NUDGE_SAFETY = ("Your response above was stopped by a safety classifier — this is not a tool "
                "or API error. The rest of it was withheld.")


def iso(dt):
    return dt.strftime("%Y-%m-%dT%H:%M:%S.000Z")


def user(text, ts, **extra):
    rec = {"type": "user", "message": {"role": "user", "content": text}, "uuid": "u-" + ts}
    if ts:
        rec["timestamp"] = ts
    rec.update(extra)
    return rec


def assistant(ts, mid, out=100, model="claude-opus-5"):
    return {"type": "assistant", "timestamp": ts, "requestId": "r-" + mid,
            "message": {"id": mid, "role": "assistant", "model": model,
                        "content": [{"type": "text", "text": "x" * 40}],
                        "usage": {"input_tokens": 10, "output_tokens": out,
                                  "cache_creation_input_tokens": 0, "cache_read_input_tokens": 0}}}


def write_jsonl(path, records, mtime=None):
    with open(path, "w", encoding="utf-8") as fh:
        for r in records:
            fh.write(json.dumps(r) + "\n")
    if mtime is not None:
        os.utime(path, (mtime, mtime))


class Fixture(unittest.TestCase):
    def setUp(self):
        self.root = tempfile.mkdtemp(prefix="gripe-miner-test-")
        self.proj = os.path.join(self.root, "C--dev-proj")
        os.mkdir(self.proj)
        self.now = datetime.datetime(2026, 10, 7, 12, 0, 0, tzinfo=datetime.timezone.utc)

    def tearDown(self):
        shutil.rmtree(self.root, ignore_errors=True)

    def at(self, days_ago, seconds=0):
        return iso(self.now - datetime.timedelta(days=days_ago, seconds=-seconds))

    def cutoff(self, days):
        return (self.now - datetime.timedelta(days=days)).timestamp()

    def session(self, name, records, mtime=None):
        path = os.path.join(self.proj, name + ".jsonl")
        write_jsonl(path, records, mtime)
        return path


# --- bug 1: local-command-caveat content leaked through the tag sweep ----------

class TestCaveatStripping(Fixture):
    def test_caveat_block_is_dropped_whole(self):
        self.assertEqual(strip_injections(CAVEAT), "")
        self.assertEqual(strip_injections(CAVEAT + "\n\n<command-name>/clear</command-name>"), "")

    def test_other_wrapper_tags_drop_their_content(self):
        text = ("<local-command-stdout>Set model to opus</local-command-stdout>"
                "<ide_opened_file>The user opened the file /x/y.py in the IDE.</ide_opened_file>"
                "<ide_selection>def foo(): pass</ide_selection>"
                "<system-reminder>Contents of CLAUDE.md: never do X</system-reminder>"
                "please fix the login bug")
        self.assertEqual(strip_injections(text), "please fix the login bug")

    def test_unknown_tags_only_lose_the_tag(self):
        self.assertEqual(strip_injections("<b>bold</b> ask"), "bold ask")

    def test_caveat_record_never_becomes_a_prompt(self):
        self.session("s1", [
            user(CAVEAT, self.at(1), isMeta=True),
            user("<command-name>/clear</command-name><command-message>clear</command-message>"
                 "<command-args></command-args>", self.at(1, 1)),
            user("<local-command-stdout></local-command-stdout>", self.at(1, 2)),
            user("fix the flaky login test please", self.at(1, 60), promptSource="typed", turnOrigin="human"),
            assistant(self.at(1, 65), "m1"),
        ])
        prompts = list(iter_prompts([self.proj], self.cutoff(30)))
        texts = [p["text"] for p in prompts]
        self.assertNotIn("Caveat", " ".join(texts))
        self.assertEqual([p["text"] for p in prompts if p["origin"] == "human"],
                         ["fix the flaky login test please"])
        # mine() (gripes/patterns) must not see the caveat either
        hits, _ = mine([self.proj], self.cutoff(30), lambda t: (None, t))
        self.assertEqual([h[1] for h in hits], ["fix the flaky login test please"])


# --- bug 2: resume nudge reworded, INJECTED_RE only knew the old form ---------

class TestResumeNudge(unittest.TestCase):
    POSITIVE = [
        NUDGE_NEW, NUDGE_OLD, NUDGE_SAFETY,
        "Your response was interrupted. Continue.",
        "Your reply above got cut off, please continue from where it stops.",
        "Your output has been truncated — resume.",
        "The previous response was cut off. Continue.",
        "Output token limit hit — please continue.",
        "[Request interrupted by user for tool use]",
    ]
    NEGATIVE = [
        "your response above was good but add tests for the edge cases",
        "cut off the trailing whitespace in the output file",
        "the deploy was interrupted by a network error, rerun it",
        "resume the paused download job and report progress",
        "truncate the log table to the last 500 rows",
        "stop the dev server and restart it on port 3002",
        "your response format should be a markdown table",
    ]

    def test_positives_are_injected(self):
        for text in self.POSITIVE:
            self.assertIsNotNone(INJECTED_RE.match(text), text)
            self.assertEqual(ineligible_reason({"text": text, "origin": "unknown"}), "injected", text)
            self.assertEqual(ineligible_reason({"text": text, "origin": "human"}), "injected", text)

    def test_negatives_stay_asks(self):
        for text in self.NEGATIVE:
            self.assertIsNone(INJECTED_RE.match(text), text)
            self.assertIsNone(ineligible_reason({"text": text, "origin": "human"}), text)

    def test_continue_nudges_are_acks_not_asks(self):
        for text in ["Continue from where you left off.", "resume where you left off",
                     "please pick up where you left off", "continue"]:
            self.assertIsNotNone(ACK_RE.match(text), text)
            self.assertEqual(ineligible_reason({"text": text, "origin": "human"}), "ack", text)
        self.assertIsNone(ACK_RE.match("continue the migration but skip the users table"))

    def test_nudge_never_clusters_even_when_tagged_human(self):
        prompts = [{"text": NUDGE_NEW, "origin": "human", "session": f"s{i}", "project": "p",
                    "date": "2026-10-01", "usage": transcripts.new_usage(), "turns": 1,
                    "models": set(), "estimated": False} for i in range(5)]
        clusters, stats = cluster(prompts)
        self.assertEqual(clusters, [])
        self.assertEqual(stats["skipped"]["injected"], 5)


# --- bug 3: --days compared only file mtime ---------------------------------

class TestDaysWindow(Fixture):
    def _long_session(self):
        # One session file touched today whose first prompts are months old.
        return self.session("long", [
            user("deploy the welcome screen to staging", self.at(90), promptSource="typed", turnOrigin="human"),
            assistant(self.at(90, 5), "old1", out=1000),
            assistant(self.at(90, 9), "old2", out=1000),
            user("deploy the welcome screen to staging", self.at(40), promptSource="typed", turnOrigin="human"),
            assistant(self.at(40, 5), "mid1", out=500),
            user("run the full test suite and summarize failures", self.at(2),
                 promptSource="typed", turnOrigin="human"),
            assistant(self.at(2, 5), "new1", out=70),
            assistant(self.at(2, 9), "new2", out=30),
        ])

    def test_prompts_and_usage_are_filtered_per_message(self):
        self._long_session()
        prompts = list(iter_prompts([self.proj], self.cutoff(14)))
        self.assertEqual([p["text"] for p in prompts], ["run the full test suite and summarize failures"])
        self.assertEqual(usage_totals(prompts)["output"], 100)
        self.assertEqual(prompts[0]["turns"], 2)
        # A 60-day window keeps the 40-day-old prompt but still drops the 90-day one.
        prompts = list(iter_prompts([self.proj], self.cutoff(60)))
        self.assertEqual([p["date"] for p in prompts], [self.at(40)[:10], self.at(2)[:10]])
        self.assertEqual(usage_totals(prompts)["output"], 600)

    def test_gripe_and_pattern_mine_use_the_same_window(self):
        self.session("long", [
            user("why does this keep resetting every time, so annoying", self.at(90),
                 promptSource="typed", turnOrigin="human"),
            user("this is so slow, why does the build take forever", self.at(2),
                 promptSource="typed", turnOrigin="human"),
        ])
        hits, scanned = mine([self.proj], self.cutoff(14), classify_gripe)
        self.assertEqual(scanned, 1)
        self.assertEqual([h[0] for h in hits], [self.at(2)[:10]])

    def test_record_without_timestamp_falls_back_to_file_mtime(self):
        recent = self.session("nots", [
            user("rebuild the docker image and restart the stack", "", promptSource="typed", turnOrigin="human"),
            assistant("", "a1", out=5),
        ], mtime=self.now.timestamp() - 3600)
        prompts = list(iter_prompts([self.proj], self.cutoff(14)))
        self.assertEqual(len(prompts), 1)
        self.assertEqual(prompts[0]["usage"]["output"], 5)
        os.utime(recent, (self.cutoff(30), self.cutoff(30)))
        self.assertEqual(list(iter_prompts([self.proj], self.cutoff(14))), [])

    def test_stale_file_is_skipped_by_mtime_prefilter(self):
        # mtime older than the cutoff => cannot hold newer messages => not scanned.
        self.session("stale", [
            user("deploy the welcome screen to staging", self.at(2), promptSource="typed", turnOrigin="human"),
        ], mtime=self.cutoff(30))
        self.assertEqual(list(iter_prompts([self.proj], self.cutoff(14))), [])
        _, scanned = mine([self.proj], self.cutoff(14), lambda t: (None, t))
        self.assertEqual(scanned, 0)

    def test_timestamp_parsing(self):
        self.assertEqual(timestamp_epoch("2026-10-07T12:00:00.000Z"), self.now.timestamp())
        self.assertEqual(timestamp_epoch("2026-10-07T12:00:00Z"), self.now.timestamp())
        self.assertEqual(timestamp_epoch("2026-10-07T12:00:00+00:00"), self.now.timestamp())
        self.assertIsNone(timestamp_epoch(""))
        self.assertIsNone(timestamp_epoch(None))
        self.assertIsNone(timestamp_epoch("yesterday"))


# --- slash-command bodies clustered as typed asks ----------------------------

class TestSlashCommands(Fixture):
    INVOKE = ("<command-message>deep-research is running…</command-message>\n"
              "<command-name>/deep-research</command-name>\n"
              "<command-args>solid state batteries</command-args>")
    BODY = ("# Deep research\n\nYou are a meticulous research assistant. Search the web for "
            "the topic given in the arguments, read at least five primary sources, and write "
            "a structured report with citations. Topic: solid state batteries")

    def test_command_invocation_parsing(self):
        self.assertEqual(command_invocation(self.INVOKE), "/deep-research solid state batteries")
        self.assertEqual(command_invocation("<command-name>/commit</command-name>"), "/commit")
        self.assertIsNone(command_invocation("run /deep-research on this"))
        self.assertIsNone(command_invocation("the transcript shows <command-name>/x</command-name> records"))

    def _run(self, body_extra):
        for i in range(3):
            self.session(f"s{i}", [
                user(self.INVOKE, self.at(3 - i), promptSource="typed", turnOrigin="human"),
                user(self.BODY, self.at(3 - i, 1), **body_extra),
                assistant(self.at(3 - i, 20), f"m{i}", out=400),
                user("ok now summarize that in three bullets", self.at(3 - i, 300),
                     promptSource="typed", turnOrigin="human"),
                assistant(self.at(3 - i, 310), f"n{i}", out=50),
            ])
        return list(iter_prompts([self.proj], self.cutoff(14)))

    def _check(self, prompts):
        self.assertEqual(len(prompts), 6)
        cmds = [p for p in prompts if p["origin"] == "command"]
        self.assertEqual(len(cmds), 3)
        self.assertTrue(all(p["text"] == "/deep-research solid state batteries" for p in cmds))
        self.assertTrue(all(p["usage"]["output"] == 400 for p in cmds), "body usage folds into the command")
        self.assertNotIn(self.BODY, [p["text"] for p in prompts])
        self.assertTrue(any("meticulous" not in p["text"] for p in prompts))
        humans = [p for p in prompts if p["origin"] == "human"]
        self.assertEqual([p["text"] for p in humans], ["ok now summarize that in three bullets"] * 3)
        clusters, stats = cluster(prompts)
        self.assertEqual(stats["skipped"]["command"], 3)
        self.assertEqual(stats["eligible"], 3)
        self.assertTrue(all("meticulous" not in m["text"] for c in clusters for m in c["members"]))
        clusters, stats = cluster(prompts, include_scripted=True)
        self.assertEqual(stats["skipped"]["command"], 0)
        self.assertEqual(stats["eligible"], 6)
        self.assertTrue(all(m["scripted"] for c in clusters for m in c["members"] if m["origin"] == "command"))

    def test_expansion_flagged_is_meta(self):
        self._check(self._run({"isMeta": True}))

    def test_expansion_without_is_meta_but_immediate(self):
        self._check(self._run({"promptSource": "typed", "turnOrigin": "human"}))

    def test_typed_message_after_a_bare_command_survives(self):
        self.session("s1", [
            user("<command-name>/clear</command-name><command-message>clear</command-message>", self.at(1)),
            user("rewrite the README install section for the namespaced commands", self.at(1, 45),
                 promptSource="typed", turnOrigin="human"),
            assistant(self.at(1, 50), "m1"),
        ])
        prompts = list(iter_prompts([self.proj], self.cutoff(14)))
        self.assertEqual([(p["origin"], p["text"][:20]) for p in prompts],
                         [("command", "/clear"), ("human", "rewrite the README i")])

    def test_mine_skips_command_bodies(self):
        self.session("s1", [
            user(self.INVOKE, self.at(1), promptSource="typed", turnOrigin="human"),
            user(self.BODY + " why does this keep breaking", self.at(1, 1), isMeta=True),
            user("why does this keep breaking every single time", self.at(1, 400),
                 promptSource="typed", turnOrigin="human"),
        ])
        hits, _ = mine([self.proj], self.cutoff(14), classify_gripe)
        self.assertEqual([h[1] for h in hits], ["why does this keep breaking every single time"])


# --- harness meta turns never split a prompt's usage --------------------------

class TestMetaTurns(Fixture):
    def test_resume_nudge_and_caption_fold_into_the_ask(self):
        self.session("s1", [
            user("write the release notes for v0.3.1", self.at(1), promptSource="typed", turnOrigin="human"),
            assistant(self.at(1, 5), "m1", out=100),
            user(NUDGE_NEW, self.at(1, 6), isMeta=True),
            assistant(self.at(1, 10), "m2", out=200),
            user("[Image: original 2080x1920, displayed at 2000x1846.]", self.at(1, 20), isMeta=True),
            assistant(self.at(1, 25), "m3", out=300),
        ])
        prompts = list(iter_prompts([self.proj], self.cutoff(14)))
        self.assertEqual(len(prompts), 1)
        self.assertEqual(prompts[0]["usage"]["output"], 600)
        self.assertEqual(prompts[0]["turns"], 3)

    def test_untagged_nudge_still_dropped_by_text(self):
        self.session("s1", [
            user("write the release notes for v0.3.1", self.at(1), promptSource="typed", turnOrigin="human"),
            assistant(self.at(1, 5), "m1", out=100),
            user(NUDGE_NEW, self.at(1, 6)),
            assistant(self.at(1, 10), "m2", out=200),
        ])
        prompts = list(iter_prompts([self.proj], self.cutoff(14)))
        self.assertEqual(len(prompts), 2)
        _, stats = cluster(prompts)
        self.assertEqual(stats["skipped"]["injected"], 1)


if __name__ == "__main__":
    unittest.main()
