"""Shared Claude Code transcript access for all three miners (gripes, session
patterns, repeated asks).

No classification lives here — this only locates a project's transcript folder and
walks the human-typed messages inside it. mine_gripes.py and mine_patterns.py each
supply a `classify(text) -> (label, dedupe_key) | None` callback that decides what
counts for their lens. mine_asks.py uses iter_prompts() instead, which also carries
each prompt's token usage and origin metadata.

Stdlib only. Reads nothing but local ~/.claude transcripts. No network calls.
"""
import calendar
import datetime
import glob
import json
import os
import re

# Harness wrapper tags whose CONTENT is harness-written, never typed, so the whole
# block is dropped. The generic sweep below only removes tags, so anything missing
# from this list leaks its body into the classifiers — that is exactly how the
# local-command caveat sentence became a "repeated ask" in v0.3.0.
#   system-reminder        — harness context (CLAUDE.md contents, memory, etc.)
#   command-name/-message/-args — a slash-command invocation (handled separately
#                            by iter_prompts, which keeps the name + args)
#   local-command-stdout/-stderr — output of a local (built-in) slash command
#   local-command-caveat   — "Caveat: The messages below were generated by the
#                            user while running local commands..."
#   user-memory-input      — memory the harness fed in
#   ide_opened_file / ide_selection — IDE-extension context about open files
CONTENT_STRIP_TAGS = (
    "system-reminder", "command-name", "command-message", "command-args",
    "local-command-stdout", "local-command-stderr", "local-command-caveat",
    "user-memory-input", "ide_opened_file", "ide_selection",
)
_CONTENT_STRIP_RE = re.compile(
    r"<(" + "|".join(re.escape(t) for t in CONTENT_STRIP_TAGS) + r")(?:\s[^>]*)?>.*?</\1>\s*",
    re.DOTALL | re.IGNORECASE,
)
# A wrapper that was opened but never closed (truncated record): drop to the end.
_UNCLOSED_STRIP_RE = re.compile(
    r"<(" + "|".join(re.escape(t) for t in CONTENT_STRIP_TAGS) + r")(?:\s[^>]*)?>.*$",
    re.DOTALL | re.IGNORECASE,
)
# An invocation record starts with one of the command tags; prose that merely
# mentions "<command-name>" (a pasted doc, a bug report) must not count.
_COMMAND_RECORD_RE = re.compile(r"\s*<command-(?:name|message|args)>", re.IGNORECASE)
_COMMAND_NAME_RE = re.compile(r"<command-name>\s*(.*?)\s*</command-name>", re.DOTALL | re.IGNORECASE)
_COMMAND_ARGS_RE = re.compile(r"<command-args>\s*(.*?)\s*</command-args>", re.DOTALL | re.IGNORECASE)

# A slash command's expanded body is written by the harness as the user turn that
# immediately follows the <command-name> record. It normally carries isMeta=true;
# when it doesn't, it still lands within a second or two of the invocation, so a
# follow-up typed by a person is told apart by the gap.
COMMAND_EXPANSION_WINDOW_S = 10


def strip_injections(text):
    """Remove harness/system-injected tag blocks that get prepended to user turns,
    so classifiers only see what the human actually typed."""
    text = re.sub(r"<task-notification>.*?</status>\s*", " ", text, flags=re.DOTALL | re.IGNORECASE)
    text = _CONTENT_STRIP_RE.sub(" ", text)
    text = _UNCLOSED_STRIP_RE.sub(" ", text)
    text = re.sub(r"</?[a-z][^>]*>", " ", text, flags=re.IGNORECASE)
    return " ".join(text.split())


def command_invocation(text):
    """If `text` is a slash-command invocation record (<command-name>...), return
    the command line a person would have typed: "/name args". Else None."""
    if not isinstance(text, str) or not _COMMAND_RECORD_RE.match(text):
        return None
    m = _COMMAND_NAME_RE.search(text)
    if not m:
        return None
    name = " ".join(m.group(1).split())
    if not name:
        return None
    if not name.startswith("/"):
        name = "/" + name
    a = _COMMAND_ARGS_RE.search(text)
    args = " ".join(a.group(1).split()) if a else ""
    return (name + " " + args).strip()


def timestamp_epoch(ts):
    """Seconds since the epoch for a transcript timestamp ("2026-10-07T12:34:56.789Z"),
    or None when it is missing or unparseable. Naive values are read as UTC."""
    if not isinstance(ts, str) or not ts:
        return None
    s = ts.strip()
    if s[-1:] in ("Z", "z"):
        s = s[:-1] + "+00:00"
    try:
        dt = datetime.datetime.fromisoformat(s)
    except ValueError:
        m = re.match(r"(\d{4})-(\d{2})-(\d{2})[T ](\d{2}):(\d{2}):(\d{2})", s)
        if not m:
            return None
        return float(calendar.timegm(tuple(int(x) for x in m.groups()) + (0, 0, 0)))
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=datetime.timezone.utc)
    return dt.timestamp()


def _record_epoch(record, fallback):
    """When a message was written: its own timestamp, else the file's mtime."""
    t = timestamp_epoch(record.get("timestamp"))
    return fallback if t is None else t


def _file_in_window(path, cutoff):
    """mtime pre-filter. A file last written before the cutoff cannot contain a
    message newer than the cutoff, so skipping it is safe; a file written after it
    may still hold months of older messages, which is why every message is also
    checked individually. Returns the mtime, or None to skip the file."""
    try:
        mtime = os.path.getmtime(path)
    except OSError:
        return None
    return mtime if mtime >= cutoff else None


def transcript_dir(cwd):
    """Claude Code stores a project's transcripts under a folder whose name is the
    absolute cwd with every non-alphanumeric char replaced by '-'.
    e.g.  C:\\dev\\New project  ->  C--dev-New-project"""
    enc = re.sub(r"[^A-Za-z0-9]", "-", os.path.abspath(cwd))
    d = os.path.join(os.path.expanduser("~"), ".claude", "projects", enc)
    return d if os.path.isdir(d) else None


def all_project_dirs():
    root = os.path.join(os.path.expanduser("~"), ".claude", "projects")
    return [p for p in glob.glob(os.path.join(root, "*")) if os.path.isdir(p)]


def mine(dirs, cutoff, classify):
    """Walk every project dir, run `classify(text)` on each genuinely human-typed
    message written at or after `cutoff` (epoch seconds), and collect what it keeps.

    classify(text) must return None (skip) or a (label, dedupe_key) tuple — label
    is lens-specific (e.g. a pattern theme, or None for gripes), dedupe_key groups
    near-duplicates so only the first occurrence is kept.

    The window is applied per message (by its timestamp; file mtime only when a
    record has none), not per file — one recently-touched session file no longer
    drags its whole history into the window.

    Returns (hits, scanned) where hits is a list of (timestamp, snippet, label),
    newest-file-scanned-first is NOT guaranteed — callers sort/limit themselves.
    """
    hits, seen, scanned = [], set(), 0
    for tdir in dirs:
        for path in glob.glob(os.path.join(tdir, "*.jsonl")):
            mtime = _file_in_window(path, cutoff)
            if mtime is None:
                continue
            scanned += 1
            after_command = None  # epoch of a slash-command invocation just seen
            try:
                with open(path, encoding="utf-8") as fh:
                    for line in fh:
                        if '"user"' not in line:
                            continue
                        try:
                            o = json.loads(line)
                        except (json.JSONDecodeError, ValueError):
                            continue
                        if o.get("type") != "user" or o.get("isSidechain"):
                            continue
                        if "toolUseResult" in o:
                            continue
                        msg = o.get("message") or {}
                        if msg.get("role") != "user":
                            continue
                        content = msg.get("content")
                        if not isinstance(content, str):
                            continue  # list content = tool result, not a typed message
                        when = _record_epoch(o, mtime)
                        if command_invocation(content) is not None:
                            after_command = when
                            continue
                        if o.get("isMeta") or _is_command_expansion(o, when, after_command):
                            after_command = None
                            continue  # harness-written (caption, nudge, command body)
                        after_command = None
                        if when < cutoff:
                            continue
                        text = strip_injections(content).strip()
                        if not text or len(text) < 12:
                            continue
                        result = classify(text)
                        if result is None:
                            continue
                        label, key = result
                        if key in seen:
                            continue
                        seen.add(key)
                        ts = (o.get("timestamp") or "")[:10]
                        hits.append((ts, text[:280], label))
            except OSError:
                continue
    return hits, scanned


# ---------------------------------------------------------------------------
# "Automate this" lens support (v0.3.0). Additive only: nothing above changed.
# ---------------------------------------------------------------------------

def prompt_origin(record):
    """Classify a user-turn JSONL record by the metadata Claude Code writes on it,
    without looking at the text.

    Returns one of:
      "human"    — a person typed it (turnOrigin "human" or promptSource "typed")
      "scripted" — sent programmatically: `claude -p`, the Agent SDK, a cron job
                   (promptSource "sdk")
      "injected" — written by the harness itself: task notifications, peer-agent
                   messages, other system-sourced turns, and any record flagged
                   isMeta (image captions, resume nudges, command expansions)
      "unknown"  — the record carries neither field. Older Claude Code versions
                   never wrote them, and current ones omit them on some turns the
                   harness generates (image captions, token-limit notices), so
                   callers must fall back to a text test for this bucket.

    iter_prompts() additionally yields "command" for slash-command invocations
    (<command-name> records), which carry no origin field worth reading.

    Field names and values verified against real transcripts written by Claude
    Code 2.1.258 and 2.1.278 (promptSource: typed/sdk/system; turnOrigin:
    human/sdk/task_notification/peer; isMeta on captions and nudges).
    """
    if record.get("isMeta"):
        return "injected"
    turn_origin = record.get("turnOrigin")
    prompt_source = record.get("promptSource")
    if turn_origin == "human" or prompt_source == "typed":
        return "human"
    if turn_origin in ("task_notification", "peer") or prompt_source == "system":
        return "injected"
    if prompt_source == "sdk" or turn_origin == "sdk":
        return "scripted"
    return "unknown"


def _is_command_expansion(record, when, after_command):
    """True when this user record is the harness-written body of the slash command
    whose invocation record was the previous user turn."""
    if after_command is None:
        return False
    if record.get("isMeta"):
        return True
    # No isMeta flag: only the gap tells a harness expansion (written at once)
    # from a message the person typed after a command that expanded to nothing.
    return 0 <= when - after_command <= COMMAND_EXPANSION_WINDOW_S


def _typed_text(content):
    """The readable text of a user turn, or None when it isn't a prompt at all.
    String content is a typed message. A list is accepted only when every block is
    a text block (some SDK clients send prompts that way); anything carrying a
    tool_result is the harness feeding a tool's output back, not a new prompt."""
    if isinstance(content, str):
        return content
    if isinstance(content, list) and content:
        parts = []
        for block in content:
            if not isinstance(block, dict) or block.get("type") != "text":
                return None
            parts.append(block.get("text") or "")
        return "\n".join(parts)
    return None


def _text_chars(content):
    if isinstance(content, str):
        return len(content)
    chars = 0
    if isinstance(content, list):
        for block in content:
            if isinstance(block, dict) and isinstance(block.get("text"), str):
                chars += len(block["text"])
    return chars


def new_usage():
    """One prompt's attributed token usage, split the way the API reports it.
    cache_create_1h is the subset of cache_create written with the 1-hour TTL
    (billed 2x instead of 1.25x) — kept separate so cost weighting can be exact."""
    return {"input": 0, "output": 0, "cache_create": 0, "cache_create_1h": 0, "cache_read": 0}


def iter_prompts(dirs, cutoff):
    """Walk every project dir and yield one record per user prompt written at or
    after `cutoff` (epoch seconds), carrying the token usage of every assistant
    message that followed it up to the next prompt.

    Yielded dict: {"project", "session", "timestamp", "date", "origin", "text",
    "usage": new_usage(), "turns", "models": set(), "estimated"}.

    How attribution works, and the traps it avoids:
    - Usage comes from message.usage on assistant lines (input_tokens,
      output_tokens, cache_creation_input_tokens, cache_read_input_tokens, plus
      the cache_creation.ephemeral_1h_input_tokens breakdown) — names verified
      against real transcripts, not assumed.
    - Claude Code writes one JSONL line per streamed content block, all sharing
      the same message.id and the SAME usage snapshot (verified: 0 differing
      snapshots across 8,456 message ids on this box, up to 19 lines per id).
      Each id is counted once per session file; requestId / line uuid are the
      fallbacks when message.id is missing.
    - Tool results and harness-generated turns (isMeta records: image captions,
      resume nudges, slash-command bodies; sidechain prompts) do NOT start a new
      prompt: their follow-on usage stays with the prompt that caused it.
      API-error lines carry zero usage and are skipped entirely.
    - A slash-command invocation (<command-name> record) IS a prompt, with
      origin "command" and text "/name args"; the expanded body the harness
      writes right after it is folded into that prompt, never clustered.
    - The time window is per message: a prompt or assistant turn older than the
      cutoff is dropped even when its file was touched recently. A record with
      no timestamp inherits the file mtime. Usage attached to an out-of-window
      prompt is dropped with it.
    - A turn with no usage field at all is estimated at len(text)//4 output
      tokens and the record is flagged "estimated" so nothing exact-looking is
      ever fabricated. Usage before the first prompt in a file (resumed
      sessions) has nothing to attach to and is dropped, so totals are a floor.
    - Subagent transcripts (<session>/subagents/*.jsonl) are not walked; their
      spend is not attributed. Also a floor.

    Every prompt is yielded regardless of origin — callers decide what counts.
    """
    for tdir in dirs:
        for path in glob.glob(os.path.join(tdir, "*.jsonl")):
            mtime = _file_in_window(path, cutoff)
            if mtime is None:
                continue
            session_id = os.path.splitext(os.path.basename(path))[0]
            current = None
            seen_ids = set()
            after_command = None
            try:
                with open(path, encoding="utf-8") as fh:
                    for line in fh:
                        if '"user"' not in line and '"assistant"' not in line:
                            continue
                        try:
                            o = json.loads(line)
                        except (json.JSONDecodeError, ValueError):
                            continue
                        otype = o.get("type")
                        msg = o.get("message") or {}
                        if otype == "user":
                            if o.get("isSidechain") or "toolUseResult" in o:
                                continue
                            if msg.get("role") != "user":
                                continue
                            raw = _typed_text(msg.get("content"))
                            if raw is None:
                                continue
                            when = _record_epoch(o, mtime)
                            cmd = command_invocation(raw)
                            if cmd is None:
                                if o.get("isMeta") or _is_command_expansion(o, when, after_command):
                                    after_command = None
                                    continue  # harness text: usage stays with `current`
                                after_command = None
                                text = strip_injections(raw).strip()
                                if not text or len(text) < 12:
                                    continue
                                origin = prompt_origin(o)
                            else:
                                after_command = when
                                text, origin = cmd, "command"
                            if current is not None and current.pop("_in_window"):
                                yield current
                            ts = o.get("timestamp") or ""
                            current = {
                                "project": tdir,
                                "session": session_id,
                                "timestamp": ts,
                                "date": ts[:10],
                                "origin": origin,
                                "text": text,
                                "usage": new_usage(),
                                "turns": 0,
                                "models": set(),
                                "estimated": False,
                                "_in_window": when >= cutoff,
                            }
                        elif otype == "assistant":
                            if current is None or o.get("isApiErrorMessage"):
                                continue
                            if _record_epoch(o, mtime) < cutoff:
                                continue
                            key = msg.get("id") or o.get("requestId") or o.get("uuid")
                            if key in seen_ids:
                                continue
                            seen_ids.add(key)
                            current["turns"] += 1
                            model = msg.get("model")
                            if model:
                                current["models"].add(model)
                            usage = msg.get("usage")
                            if isinstance(usage, dict):
                                u = current["usage"]
                                u["input"] += usage.get("input_tokens") or 0
                                u["output"] += usage.get("output_tokens") or 0
                                u["cache_create"] += usage.get("cache_creation_input_tokens") or 0
                                breakdown = usage.get("cache_creation")
                                if isinstance(breakdown, dict):
                                    u["cache_create_1h"] += breakdown.get("ephemeral_1h_input_tokens") or 0
                                u["cache_read"] += usage.get("cache_read_input_tokens") or 0
                            else:
                                current["usage"]["output"] += _text_chars(msg.get("content")) // 4
                                current["estimated"] = True
                if current is not None and current.pop("_in_window"):
                    yield current
            except OSError:
                continue
